blank_issues_enabled: false
contact_links:
  - name: Boulevard Consulting Developer Slack Channel
    url: https://app.slack.com/client/TRLLL05LH/CTG3692FN
    about: Please ask and answer other questions here.
